export const TaskActionTypes ={
    SET_TASKS: 'SET_TASKS',
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK',
    TOGGLE_TASK_COMPLETION: 'TOGGLE_TASK_COMPLETION',
    SET_NEW_TASK_DESCRIPTION: 'SET_NEW_TASK_DESCRIPTION',
}